# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-09 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_staff',
        ),
    ]
