# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-09 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0002_remove_restaurant_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_staff',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
