# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0004_restaurant_is_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_staff_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='is_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
