# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-30 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0005_auto_20181021_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_open_wknd',
            field=models.BooleanField(default=False),
        ),
    ]
