# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-30 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0006_restaurant_is_open_wknd'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours_wknd',
            field=models.TimeField(default='0:00'),
        ),
    ]
