# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-30 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0007_restaurant_opening_hours_wknd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours_wknd',
            field=models.TimeField(),
        ),
    ]
