# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-31 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0008_auto_20181030_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='closing_hours_wknd',
            field=models.TimeField(default='0:00'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours_wknd',
            field=models.TimeField(default='0:00'),
        ),
    ]
