# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-10-31 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0010_auto_20181031_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='closing_hours_wknd',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours_wknd',
            field=models.TimeField(default='9:00'),
        ),
    ]
