# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-11 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0011_auto_20181031_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avg_rating',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
