# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-11 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatatdcu', '0012_auto_20181211_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='avg_rating',
            field=models.IntegerField(),
        ),
    ]
